# Site settings
title: infinimesh blog
tag_text: software, tech and development
description: infinimesh IoT is worlds first open cloud native platfrom, and here we write about our tech stack and what we do
url: "https://infinimesh.github.io"
baseurl: "/"

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
